### Задача 1

Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите M(X), D(X)

Параметр n равняется 5, так как вопросов 5, к=4, т.к. вариантов ответов 4 а вероятность правильного ответа P(A) = 1/4 или 0.25, вероятность неправильного ответа q = 1 -p = 0.75

In [261]:
n = 5
p_a = 0.25
k = 4

M(X)=np

In [262]:
m_x = n * p_a
m_x

1.25

D(X)=npq

In [263]:
d_x = n * p_a * (1 - p_a)
d_x

0.9375

In [264]:
import numpy as np
from math import factorial

In [265]:
#Определяется число сочетаний из n элементов по k элементов в каждом (в сочетаниях порядок не важен)
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))

Возможные значения случайной величины (правильных ответов): $x_1 = 0$, $x_2 = 1$, $x_3 = 2$, $x_4 = 3$, $x_5 = 4$, $x_6 = 5$.

In [266]:
#массив значений x 
x_values = np.arange(0, n + 1)
x_values

array([0, 1, 2, 3, 4, 5])

Биномиальный закон распределения описывается __формулой Бернулли__:
$$P(X = k) = C_n^k p^k (1 - p)^{n - k}$$,
где n = 5, k = 4, p = P(+), q = 1 - p

In [267]:
#формула Бернулли:
def get_bern(x):
    return combinations(n, x)*(p_a)**x*(1 - p_a)**(n-x)

In [268]:
#массив значений вероятностей соббытий A:
x_probabilities = []

In [269]:
for i in x_values:
    x_probabilities.append(get_bern(i))
x_probabilities

[0.2373046875,
 0.3955078125,
 0.263671875,
 0.087890625,
 0.0146484375,
 0.0009765625]

In [270]:
# проверка сумма всех вероятностей = 1
np.sum(x_probabilities)

1.0

In [271]:
# распределение числа правильных ответов
p_x = dict(zip(x_values, x_probabilities))
p_x

{0: 0.2373046875,
 1: 0.3955078125,
 2: 0.263671875,
 3: 0.087890625,
 4: 0.0146484375,
 5: 0.0009765625}

In [272]:
#проверка M(X)
m = x_values.dot(x_probabilities)
print(m)

1.25


In [273]:
#проверка D(X)
y_values = x_values - m
print(y_values)

[-1.25 -0.25  0.75  1.75  2.75  3.75]


In [274]:
z_values = y_values ** 2
print(z_values)

[ 1.5625  0.0625  0.5625  3.0625  7.5625 14.0625]


In [275]:
#значение дисперсии
d = z_values.dot(x_probabilities)
print(d)

0.9375


### Задача 2
Вероятность поймать рыбу при одном забрасывании удочки равна 0.01. Какова вероятность того, что число пойманных рыб при 200 забросах удочки будет не менее 5 и не более 10?

#### формула Пуассона:
$$P(X = k) = \dfrac{a^k e ^{-a}}{k!}.$$

In [277]:
#формула Пуассона:
def puasson(a, k):
    return (a ** k) * (np.exp(-a)) / factorial(k)

In [278]:
x_probabilities = []

In [279]:
for k in k_values:
    x_probabilities.append(puasson(a, k))
x_probabilities

[0.03608940886309672,
 0.012029802954365574,
 0.0034370865583901638,
 0.0008592716395975409,
 0.00019094925324389798,
 3.8189850648779595e-05]

In [280]:
# проверка сумма всех вероятностей = 1
sum_pr = np.sum(x_probabilities)
f"сумма вероятностей поймать от {k_values[0]} до {k_values[-1]} рыбин, равна {sum_pr}"

'сумма вероятностей поймать от 5 до 10 рыбин, равна 0.052644709119342686'

### Задача 3
В условиях предыдущей задачи сколько забросов удочки нужно сделать чтобы быть уверенным с вероятностью 0.9, что хотя бы 10 раз будет поймана рыба?

Подсказка. Как посчитать P(X >= k) для величины X, имеющей биномиальное распределение? Здесь предстоит немножко покодить.

#### формула Пуассона:
$$P(X = k) = \dfrac{a^k e ^{-a}}{k!}.$$

$P(X = k) = 0.9 $

#### по условиям задачи
$n=?$; 
$p=0.01$;
$a = np = n * 0.01 $; $10 \leq k $

In [294]:
# 0.9 = (0.01 * n) **10  * (np.exp(-0.01 * n)) / factorial(10)
# 0.9 * factorial(10) / 0.01**10 = n**10 *  (np.exp(-0.01 * n))
# 0.9 * factorial(10) / 0.01**10 = n**10 / np.exp(0.01 * n)

3.2659199999999994e+26

In [295]:
# используется формула Пуассона
def sum_P(n):
    p = 0
    for i in range(10, n + 1):
        p = p + puasson(0.01 * n, i)
        if puasson(0.01 * n, i) < 10**(-17):
            #print('значение стремится к 0')
            break
    return p

n = 10
while sum_P(n) < 0.9:
    n = n + 1
print(f'Вероятность {sum_P(n)}, что хотя бы 10 раз будет поймана рыба, можно получить, сделав не менее {n} забросов удочки')

Вероятность 0.9001760722984113, что хотя бы 10 раз будет поймана рыба, можно получить, сделав не менее 1421 забросов удочки
